version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables :
      - name: sales
        identifier: raw_gz_sales
        description: table des données sur les ventes
      - name: product
        identifier: raw_gz_product
        description: table des données sur les produits
      - name: ship
        identifier: raw_gz_ship
        description: table des données sur les livraisons